version: '2'
services:
  dbb:
    image: postgres:9.5.3
    container_name:
    environment:
    - POSTGRES_DB=
    - POSTGRES_USER=
    - POSTGRES_PASSWORD=
    ports:
      - "5432:5432"
    volumes:
      - /opt/Keepassa/db/:/var/lib/postgresql/data
    
